server:
  port: 8181
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

management:
  info:
    git:
      enabled: true
      mode: full
    endpoints:
      web:
        exposure:
          include: health, info, env
    endpoint:
      health:
        show-components: always
        show-details: always

logging.level:
  root: INFO
  ReportLogger: ERROR

spring:
  jackson.default-property-inclusion: non_null
  main.allow-circular-references: true
  kafka:
    bootstrap-servers: 'ENTER KAFKA SERVER HOST:PORT'
    producer:
      topic: 'ENTER TOPIC NAME'
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer